name: CI
on:
  push:
  pull_request:
    
jobs:
  build:
    runs-on: self-hosted
    env: # Or as an environment variable
      es_api_token: ${{ secrets.ES_API_TOKEN }}
      shop: ${{ secrets.shop }}
    steps:
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: curl --location --request POST "$es_domain/api/containers/test/store" --form "token=$es_api_token" --form "shop=$shop" --form "branch=${GITHUB_REF##*/}"

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
